{% set version = "1.12.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rje
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rje_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rje/rje_{{ version }}.tar.gz
  sha256: 10dcb0f1a6a617940f59fda1e989fc1124fe737dceb922a27b3ee95bece2411d

build:
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-knitr
  run:
    - r-base
    - r-knitr

test:
  commands:
    - $R -e "library('rje')"           # [not win]
    - "\"%R%\" -e \"library('rje')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rje
  license: GPL-2.0-or-later
  summary: A series of functions in some way considered useful to the author.  These include functions for subsetting tables and generating indices for arrays, conditioning and intervening in probability distributions, generating combinations and more...
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: rje
# Type: Package
# Title: Miscellaneous Useful Functions for Statistics
# Version: 1.10.10
# Authors@R: c(person("Robin", "Evans", email="evans@stats.ox.ac.uk", role=c("aut", "cre")), person("Mathias", "Drton", role=c("ctb")))
# Description: A series of functions in some way considered useful to the author.  These include functions for subsetting tables and generating indices for arrays, conditioning and intervening in probability distributions, generating combinations and more...
# Depends: R (>= 2.0.0),
# License: GPL (>= 2)
# LazyLoad: yes
# Imports: knitr
# Suggests: testthat, rmarkdown
# VignetteBuilder: knitr
# Packaged: 2019-08-26 11:15:48 UTC; evans
# Author: Robin Evans [aut, cre], Mathias Drton [ctb]
# Maintainer: Robin Evans <evans@stats.ox.ac.uk>
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2019-08-28 04:30:02 UTC
