{% set version = "1.10.10" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rje
  version: {{ version|replace("-", "_") }}

source:
  fn: rje_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rje_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rje/rje_{{ version }}.tar.gz
  sha256: 42ffe1a9d4b0bea2dcc855d5855bba50fbae8b1963db2729e72db1a6cb461bc4

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed  # [win]
    - {{posix}}coreutils  # [win]
  host:
    - r-base
  run:
    - r-base
    - libgfortran-ng             # [not win]
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('rje')"           # [not win]
    - "\"%R%\" -e \"library('rje')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rje
  license: GPL (>= 2)
  summary: A series of useful functions, some available in different forms in other packages,
    but which have been extended, sped up, or otherwise modified in some way considered
    useful to the author.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
