# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangtarget_platformosx-64
    - CONFIG=osx_c_compilertoolchain_ctarget_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "USu4w+nvhOX+7KjY9E5SMC1b9x9TvtA8XvB6pK/JdvpeNa2B2wd4qncp5ewHdggAg2jPOYMr9umNTuA13lsPXECjUSTaOCDAR3u8QDU8Ymxr0Pl81FKGTGq5t3eH5vY42JPVU/tvv9uYgdi5ZZuw6QRVKn+cNQCCKByd9U+sr6LoTN9IcdGvBzlKCBtog0fEvlgV6WRUZ1fIcMnedgzO8yhbqKUu8m2PH1P+TlK6kOTullgnQglYLTqPKqIbf/jjBqGxjJ+KSKnhBXSgTHCubeUh7WCepcwuJGt7J1DBMeEW0jevonpdWD84Ga5Pa8Dcx7ntzYHRVUKaYINsITHuJ+6ivKsv/FSZdnfD8O67EpdgAFmZjsu+ue/+VxaLJ3dxTD1JiMW4ktAW5u0t3Oq+3N7jOS6aKC6a02FiwGMoCMGhgng1V3gPJjNm8gB7hA+UH1J2Xvk7aZ6/j9xovBAAu4qeszdQGprgTdFNtuP+n7R147+at7ZivhUpr5CzIzz0VSxN/BEyPz54C91nZzChVcTCp+8bGs9p2ijH278E1wVBsFPVLnphSxhFIxULrClKC/eFWIs0D7Hhte28moovOOe22B3urMKdvraN6F85KuM7JlJvQhsbbVnUSAnPgKD/Fa4M5jmcn+BcmcHOCiiJzSecn/eztAnXmKejYa4vqHk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
