travis:
  secure:
    BINSTAR_TOKEN: P3L4OQf31rFsFlYZBDKqpvkvk2UmHOSpyyUG5gSvcYHm/LnVmglD0coWrtoAeBJcfak75GWO5bXDj7Jr3EqKVFhGB6pY76YvXY38Uz04SCmXi+YTcGrI1XIJMKP8tVESSK85dlTV+rPfN9n9H8jqNlo0GjVKBnVa52jm0rF7+raxs2idoadnu7KmyUg0Z47M2GzZBf56Quiq80RwTDHvFfS+U8ggwdstzqfM2RZkI9iLpADnxtLZlE1ME6DUqAnMf1vXR5DuEotA0SDS8JjgIHMlgesQm77L9vo9rdXbqeDiKaKW33/Z1nuKy6HngEPgOASj2uKi2eduJZEsTAvPzAZeXKe4Oo7A/1vCCK8nMTykEQ7eJ1F8ng/sCK0nGZQRI2V+XVhV10tAyRlwyWq1pdplWyqARIrrBc4IujxqQ8Imr2iTT22DMrN088u2IN1t4kyUcz0wVTeMO21NnJpiZuGw+QJp+R69xJKMsHyVPhD4DgAcZNpx3Jz+vm3V5o3d8WRgM/cuzjv2ZThSHJ3yJXj9qhm3oobQssAu7XLNJ/RH69kFWOojsGmf4Nf8A7xaQJJohMqXaQ/KeUyt0ZZC0B/5MSoBq90+YB2aZHLOswnitl2VYcriWdOVZiDv9v1CATt0GMc6efFfardLhqBUqc5FDLmlnMO+5qBtYjtZc58=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
