appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: USu4w+nvhOX+7KjY9E5SMC1b9x9TvtA8XvB6pK/JdvpeNa2B2wd4qncp5ewHdggAg2jPOYMr9umNTuA13lsPXECjUSTaOCDAR3u8QDU8Ymxr0Pl81FKGTGq5t3eH5vY42JPVU/tvv9uYgdi5ZZuw6QRVKn+cNQCCKByd9U+sr6LoTN9IcdGvBzlKCBtog0fEvlgV6WRUZ1fIcMnedgzO8yhbqKUu8m2PH1P+TlK6kOTullgnQglYLTqPKqIbf/jjBqGxjJ+KSKnhBXSgTHCubeUh7WCepcwuJGt7J1DBMeEW0jevonpdWD84Ga5Pa8Dcx7ntzYHRVUKaYINsITHuJ+6ivKsv/FSZdnfD8O67EpdgAFmZjsu+ue/+VxaLJ3dxTD1JiMW4ktAW5u0t3Oq+3N7jOS6aKC6a02FiwGMoCMGhgng1V3gPJjNm8gB7hA+UH1J2Xvk7aZ6/j9xovBAAu4qeszdQGprgTdFNtuP+n7R147+at7ZivhUpr5CzIzz0VSxN/BEyPz54C91nZzChVcTCp+8bGs9p2ijH278E1wVBsFPVLnphSxhFIxULrClKC/eFWIs0D7Hhte28moovOOe22B3urMKdvraN6F85KuM7JlJvQhsbbVnUSAnPgKD/Fa4M5jmcn+BcmcHOCiiJzSecn/eztAnXmKejYa4vqHk=}
bot:
  automerge: true
